### ISSUE TITLE
problem with BME280 values

### ISSUE THREAD

**Issue by acastanet** [pimoroni/pxt-envirobit#3]
Hello,

I have a problem with your BME280 library.
Your card work fine and is a good card for my classroom but pressure and humidity are always read 1026 and 30 !
First I suspect hardware problems but BME280 give me good values with :
https://makecode.microbit.org/pkg/makecode-extensions/bme280
Do you have a solution ?
Because add only one library is better for my little students.
Best regards,
Alex

**Comment by Gadgetoid** [comment]
It's something I'm in the process of looking into and a fix is incoming.

**Comment by acastanet** [comment]
Thanks

**Comment by Gadgetoid** [comment]
Work in progress here - https://github.com/pimoroni/pxt-envirobit/tree/fix-from-bme280

I need to pick up some hardware to test it, though! (Currently at home with a brand shiny new baby)

**Comment by Gadgetoid** [comment]
Hopefully now fixed and available in v0.0.5! Please let me know how you get on.

**Comment by acastanet** [comment]
Yes, all good.
Thanks from Marseille.
Alex
