### ISSUE TITLE
Possible bug in the library for the LEDs

### ISSUE THREAD

**Issue by ghost** [pimoroni/pxt-envirobit#5]
The LEDs don't appear to light up on the enviro:bit - I looked at the code in envirobit.ts and on line 160 it doesn't tell the 'bit to turn on p8 digitally... Please fix it!

**Comment by Gadgetoid** [comment]
The LED's are controlled by the "Set lets to %state" block. You must turn them on manually, otherwise they would interfere with ambient colour readings (light temperature, etc).

https://github.com/pimoroni/pxt-envirobit/blob/bdcf246981ae51cb094877e85758c3ee51e5495a/envirobit.ts#L428-L436

**Comment by ghost** [comment]
How?
